.base: &base
  forwardAgent: true
  multiplexing: true

18.143.189.197: &dev1
  <<: *base
  stage: "develop"
  user: "ec2-user"
  port: 22
  identityFile: "/home/kumo/.ssh/test-server.pem"
  deploy_path: "/var/www/{{application}}"
  branch: "develop"

#18.143.189.197:
#  <<: *dev1
